%include	/usr/lib/rpm/macros.perl
Summary:	Demoroniser corrects incompatible HTML generated by Microsoft applications
Name:		demoroniser
Version:	19980116
Release:	1
License:	Public Domain
Group:		Applications/Text
URL:		http://www.fourmilab.ch/webtools/demoroniser/
Source0:	http://www.fourmilab.ch/webtools/%{name}/demoroniser.zip
# Source0-md5:	a0da935a4734f858ed6a9f57b70f2a66
BuildRequires:	rpm-perlprov >= 4.1-13
BuildRequires:	sed >= 4.0
BuildRequires:	unzip
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Corrects moronic and gratuitously incompatible HTML generated by
Microsoft applications. Also can be useful on just text to get rid of
the "smart quotes" Microsoft applications like to use.

%prep
%setup -qc
%{__sed} -i -e '1s,#!.*bin/perl,#!%{__perl},' demoroniser.pl

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_bindir},%{_mandir}/man1}
install demoroniser.pl $RPM_BUILD_ROOT%{_bindir}/demoroniser
cp -a demoroniser.1 $RPM_BUILD_ROOT%{_mandir}/man1

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc demoroniser.man
%attr(755,root,root) %{_bindir}/demoroniser
%{_mandir}/man1/demoroniser.1*
